### ISSUE TITLE
Alterar template de issue

### ISSUE THREAD

**Issue by Sherlockzen** [hatcoders/octopost#187]
<details open> 
  <summary>
    <b>Description</b>
  </summary>
   
 Esses campos nao sao necessarios no modelo de template no momento.
 
![image](https://github.com/Alecell/octopost/assets/61947632/71ec22b5-155e-4dd4-a62f-6ccc75a30f88)

Se conseguir, pode colocar outros modelos, como modelo de bugs, reports, etc. Exemplo: https://github.com/tajo/ladle/issues/new/choose

</details>

**Comment by mythrillium621** [comment]
Opa, me adiciona na task!

**Comment by aalmeida00** [comment]
eu quero!!!
