### ISSUE TITLE
Adicionar dependabot ao projeto

### ISSUE THREAD

**Issue by kingjotaro** [hatcoders/octopost#200]
<details open> 
  <summary>
    <b>Description</b>
  </summary>
  Adicionar Dependabot ao projeto https://github.com/dependabot
</details>

<br>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by aalmeida00** [comment]
Existe uma forma de fazer o dependabot agrupar as dependencias em um PR só, essa tarefa DEVE contemplar isso.

**Comment by lucasdcoutinh0** [comment]
eu quero!!!
