### ISSUE TITLE
Definição do template do TIL

### ISSUE THREAD

**Issue by PiluVitu** [hatcoders/octopost#212]
## Definição do template do TIL

_label: [template, til]
<br>
assignees: [assignee_username]_

<details open> 
  <summary>
    <b>Description</b>
  </summary>
   Definir um template para o til 
</details>

<details open> 
  <summary>
    <b>Modelo</b>
  </summary>
   Essa semana eu estudei bastante typescript pra tentar resolver um problema. Durante esse estudo eu descobri alguns "Utilities Types" criados pelo próprio time do typescript pra facilitar a nossa vida dificil de bugs.

Como esses "Utilities Types" funcionam
Todos eles se  beneficiam dos "Generics", algo muito util na hora de tipagem e que é presente em diversas linguagens estaticamente tipadas.

Partial
O que ele faz? Ele transforma tudo em  um objeto opcional. Olha esse exemplo:

interface User {
    id: string
    name: string
    role: "admin" | "user"
}

agora se a gente taca essa interface no Partial assim:

type OptionalUser = Partial<User>

é como se a gente fizesse isso

interface User {
    id?: string
    name?: string
    role?: "admin" | "user"
}

Required
existe o oposto do Partial que é o Required, e como o nome já diz, ele transforma tudo em required

type OptionalUser = Partial<User>

type RequiredUser = Required<OptionalUser>

e agora o tipo RequiredUser fica assim 

interface User {
    id: string
    name: string
    role: "admin" | "user"
}

Omit
agora imagina que a gente quer omitir o nome da interface User sem alterar a interface original, essa é a função do Omit.

type UserWithouName = Omit<User, "name">

Pick
e tem o contrario também, imagina que a gente quer pegar apenas a propriedade nome da interface mas sem alterar a interface original, o Pick serve pra isso.

type UserName = Pick<User, "name">

Se você quiser pegar ou excluir mais de uma propriedade, basta usar o pipeline 

type UserName = Pick<User, "id" | "name">

// ou 

type UserName = Omit<User, "id" | "name">

é possível combinar todos esses utilities types também

type UserNameOptional = Partial<Pick<User, "name">>
 
ReturnType
agora imagina que a gente tem esse tipagem de função aqui:

type HandleSomething = () => string

e você precisa ter a tipagem do retorno dessa função, pra isso existe o ReturnType

type ReturnOfHandleSomething = ReturnType<HandleSomething>

Awaited
imagina que você tem uma tipagem que é uma promise

type AwaitSomething = Promise<string>

e você quer a tipagem que essa promise vai retornar, pra isso serve o Awaited

type Result = Awaited<AwaitSomething>

agora um caso um pouco mais real, você tipou uma função que retorna uma promise e você quer separar um type diferente o retorno dessa função, simples:

type UserNameOptional = () => Promise<string>;

  

type Result = Awaited<ReturnType<UserNameOptional>>;

um caso um pouco mais real  ainda com uma função real

async function awaitSomething() {
  await new Promise(() => setTimeout(() => "demorei mas cheguei", 1000));
}

type Result = Awaited<ReturnType<typeof awaitSomething>>;
 </details>

<details open> 
  <summary>
    <b>Observações</b>
  </summary>
   Subir o til feito em um arquivo .md
</details>

**Comment by aalmeida00** [comment]
eu quero!!!
