### ISSUE TITLE
Ajustar actions para criar branch

### ISSUE THREAD

**Issue by PiluVitu** [hatcoders/octopost#213]
<details open> 
  <summary>
    <b>Description</b>
  </summary>
   O actions tem que criar uma branch sempre que uma pessoa foi assingnada na issue
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by fabiuhp** [comment]
Eu quero.

**Comment by fabiuhp** [comment]
EU QUERO!!!
