### ISSUE TITLE
Criação de um Modulo no NPM das configs eslint e Criação de Extension Pack Vscode

### ISSUE THREAD

**Issue by PiluVitu** [hatcoders/octopost#217]
- É interessante criar essas extensões para poder facilitar a integração das configs em diferentes projetos 

<details open> 
  <summary>
    <b>Description</b>
  </summary>
   
- [Elsint Repo da Rocket](https://github.com/Rocketseat/eslint-config-rocketseat/blob/main/node.js)
- [Base Pack VsCode](https://marketplace.visualstudio.com/items?itemName=PiluVitu.pilutech-base-pack)
</details>

**Comment by Alecell** [comment]
### Obrigado por abrir a issue
### Verifique os nossos guidelines:
- [Código de conduta](https://github.com/Alecell/octopost/blob/master/CODE_OF_CONDUCT.md)
- [Contribuição](https://github.com/Alecell/octopost/blob/master/CONTRIBUTING.md)
- [Guia de Estilo](https://github.com/Alecell/octopost/blob/master/STYLEGUIDE.md)

**Comment by Luiginicoletti** [comment]
Eu quero!!!
